"""
Django settings for arivas project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured
from django.templatetags.static import static
from django.utils.functional import lazy
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file


def env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() in ("true", "1", "t", "yes", "y", "on")


def env_str(name, default=None, required=False):
    value = os.getenv(name)
    if value is None or not value.strip():
        if required:
            raise ImproperlyConfigured(f"Environment variable {name} is required")
        return default
    return value.strip()


def env_int(name, default):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"Environment variable {name} must be an integer") from exc


def env_list(name, default=None):
    value = os.getenv(name)
    if value is None or not value.strip():
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


def _normalize_host(value):
    host = (value or "").strip()
    if not host:
        return ""

    if "://" in host:
        parsed = urlparse(host)
        host = parsed.netloc or parsed.path

    host = host.strip().strip("/")
    if "@" in host:
        host = host.rsplit("@", 1)[-1]

    if ":" in host and not host.startswith("["):
        host = host.split(":", 1)[0]

    return host


def env_hosts(name, default=None):
    hosts = []
    for value in env_list(name, default):
        host = _normalize_host(value)
        if host and host not in hosts:
            hosts.append(host)
    return hosts


def _host_to_origin(host):
    host = (host or "").strip()
    if not host or host == "*":
        return ""

    if host.startswith("."):
        return f"https://*{host}"

    if host in ("127.0.0.1", "localhost"):
        return f"http://{host}"

    return f"https://{host}"


def normalize_csrf_origins(origins):
    normalized = []
    for value in origins:
        origin = (value or "").strip().rstrip("/")
        if not origin:
            continue

        if "://" not in origin:
            origin = _host_to_origin(_normalize_host(origin))

        if origin and origin not in normalized:
            normalized.append(origin)

    return normalized


lazy_static = lazy(static, str)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)
USE_R2 = env_bool("USE_R2", False)
R2_PUBLIC_MEDIA_URL = env_str("R2_PUBLIC_MEDIA_URL", "")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_str(
    "SECRET_KEY",
    default="dev-only-insecure-secret-key",
    required=not DEBUG,
)


default_allowed_hosts = ['127.0.0.1', 'localhost'] if DEBUG else []
ALLOWED_HOSTS = env_hosts("ALLOWED_HOSTS", default_allowed_hosts)
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS must be set when DEBUG=False")

default_csrf_origins = []
if not DEBUG:
    default_csrf_origins = [
        origin
        for origin in (_host_to_origin(host) for host in ALLOWED_HOSTS)
        if origin
    ]
CSRF_TRUSTED_ORIGINS = normalize_csrf_origins(
    env_list("CSRF_TRUSTED_ORIGINS", default_csrf_origins)
)

CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'error.log'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # 

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'django_summernote',
    'tailwind',
    'theme',  # Your Tailwind CSS app
    'fontawesomefree',
    'whitenoise.runserver_nostatic',  # Keep WhiteNoise for static file serving
]


TAILWIND_APP_NAME = 'theme'

if DEBUG:
    NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
else:
    NPM_BIN_PATH = '/usr/bin/npm'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise must be after SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ['django_browser_reload']
    MIDDLEWARE += ['django_browser_reload.middleware.BrowserReloadMiddleware'] 


ROOT_URLCONF = 'arivas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'arivas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

RUNNING_RUNSERVER = len(sys.argv) > 1 and sys.argv[1] == 'runserver'
USE_MANIFEST_STATICFILES = env_bool('USE_MANIFEST_STATICFILES', not DEBUG)

# Allow local DEBUG=False runserver without forcing collectstatic beforehand.
if RUNNING_RUNSERVER and USE_MANIFEST_STATICFILES and not (STATIC_ROOT / 'staticfiles.json').exists():
    USE_MANIFEST_STATICFILES = False

STATICFILES_STORAGE_BACKEND = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG or not USE_MANIFEST_STATICFILES
    else "arivas.storage_backends.ManifestStaticFilesStorageNoSourceMaps"
)

WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_KEEP_ONLY_HASHED_FILES = env_bool("WHITENOISE_KEEP_ONLY_HASHED_FILES", not DEBUG)
# Keep strict manifest checks in production to fail fast on broken static references.
WHITENOISE_MANIFEST_STRICT = env_bool("WHITENOISE_MANIFEST_STRICT", True)
WHITENOISE_MAX_AGE = env_int("WHITENOISE_MAX_AGE", 60 if DEBUG else 31536000)

# Media files (Uploaded images, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": STATICFILES_STORAGE_BACKEND,
    },
}

if USE_R2:
    if "storages" not in INSTALLED_APPS:
        INSTALLED_APPS.append("storages")

    R2_ACCOUNT_ID = env_str("R2_ACCOUNT_ID", "")
    R2_ACCESS_KEY_ID = env_str("R2_ACCESS_KEY_ID", "")
    R2_SECRET_ACCESS_KEY = env_str("R2_SECRET_ACCESS_KEY", "")
    R2_BUCKET_NAME = env_str("R2_BUCKET_NAME", "")
    R2_ENDPOINT_URL = env_str("R2_ENDPOINT_URL", "")
    missing_required = []
    if not R2_ACCESS_KEY_ID:
        missing_required.append("R2_ACCESS_KEY_ID")
    if not R2_SECRET_ACCESS_KEY:
        missing_required.append("R2_SECRET_ACCESS_KEY")
    if not R2_BUCKET_NAME:
        missing_required.append("R2_BUCKET_NAME")
    if not R2_PUBLIC_MEDIA_URL:
        missing_required.append("R2_PUBLIC_MEDIA_URL")

    if not (R2_ENDPOINT_URL or R2_ACCOUNT_ID):
        missing_required.append("R2_ENDPOINT_URL or R2_ACCOUNT_ID")

    if missing_required:
        raise ImproperlyConfigured(
            "R2 storage is enabled but required settings are missing: " + ", ".join(missing_required)
        )

    AWS_ACCESS_KEY_ID = R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = R2_BUCKET_NAME
    AWS_S3_REGION_NAME = os.getenv("R2_REGION", "auto")
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE = os.getenv("R2_ADDRESSING_STYLE", "path")
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": os.getenv("R2_CACHE_CONTROL", "public, max-age=86400"),
    }
    AWS_S3_ENDPOINT_URL = R2_ENDPOINT_URL or f"https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

    MEDIA_URL = R2_PUBLIC_MEDIA_URL.rstrip("/") + "/"

    STORAGES["default"] = {
        "BACKEND": "arivas.storage_backends.PublicMediaURLS3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "default_acl": None,
            "querystring_auth": False,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
        },
    }


# Additional security settings
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Keep redirect configurable to avoid proxy redirect loops in some deployments.
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)
    SECURE_HSTS_SECONDS = env_int(
        "SECURE_HSTS_SECONDS",
        31536000 if SECURE_SSL_REDIRECT else 0,
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)
    # SECURE_REFERRER_POLICY = "strict-origin"
    # SECURE_BROWSER_XSS_FILTER = True
    # SECURE_CONTENT_TYPE_NOSNIFF = True





# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SUMMERNOTE_CONFIG = {
    "iframe": True,
    "summernote": {
        "airMode": False,
        "width": "100%",
        "height": 400,
        "codemirror": {
            "mode": "htmlmixed",
            "lineNumbers": True,
            "theme": "monokai"
        },
        "toolbar": [
            ["style", ["style"]],
            ["font", ["bold", "italic", "underline", "strikethrough", "clear"]],
            ["fontname", ["fontname"]],
            ["fontsize", ["fontsize"]],
            ["color", ["forecolor", "backcolor"]],
            ["para", ["ul", "ol", "paragraph"]],
            ["height", ["height"]],
            ["table", ["table"]],
            ["insert", ["link", "picture", "video", "hr"]],
            ["view", ["fullscreen", "codeview", "help"]],
            ["misc", ["undo", "redo"]],
        ],
    },
    "css": (
        lazy_static("css/dist/styles.css"),
        lazy_static("assets/css/pages/home.css"),
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
    ),
    "css_for_inplace": (
        lazy_static("css/dist/styles.css"),
    ),
    "js_for_inplace": (),
    "disable_attachment": False,
    "attachment_require_authentication": True,
    "attachment_storage_class": None,
    "attachment_upload_to": "django-summernote/",
    "attachment_absolute_uri": False,
    "codemirror": {
        "mode": "htmlmixed",
        "lineNumbers": True,
        "theme": ""
    },
}

# Django Unfold Configuration
UNFOLD = {
    "SITE_TITLE": "Arivas Pharmaceuticals",
    "SITE_HEADER": "Arivas Admin",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("assets/images/logo.avif"),
        "dark": lambda request: static("assets/images/logo.avif"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("assets/images/logo.avif"),
        "dark": lambda request: static("assets/images/logo.avif"),
    },
    "SITE_SYMBOL": "A",  # symbol for the sidebar
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x16",
            "type": "image/png",
            "href": lambda request: static("assets/images/favicon.ico"),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "arivas.settings.environment_callback",
    # "DASHBOARD_CALLBACK": "arivas.settings.dashboard_callback",  # Temporarily disabled
    "COLORS": {
        "primary": {
            "50": "239 68 68",  # red-500 - Arivas red theme
            "100": "220 38 38",
            "200": "185 28 28",
            "300": "153 27 27",
            "400": "127 29 29",
            "500": "239 68 68",  # Main red
            "600": "220 38 38",
            "700": "185 28 28",
            "800": "153 27 27",
            "900": "127 29 29",
            "950": "69 10 10"
        },
        "secondary": {
            "50": "30 64 175",  # blue-800 - Secondary color
            "100": "29 78 216",
            "200": "37 99 235",
            "300": "59 130 246",
            "400": "96 165 250",
            "500": "147 197 253",
            "600": "191 219 254",
            "700": "219 234 254",
            "800": "239 246 255",
            "900": "59 130 246",
            "950": "30 64 175"
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇺🇸",
                "hi": "🇮🇳",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            # {
            #     "title": "Dashboard",
            #     "separator": True,
            #     "items": [
            #         {
            #             "title": "Analytics",
            #             "icon": "dashboard",
            #             "link": lambda request: "/admin/",
            #         },
            #     ],
            # },
            {
                "title": "Communications",
                "separator": True,
                "items": [
                    {
                        "title": "Enquiries",
                        "icon": "mail",
                        "link": lambda request: "/admin/app/enquiry/",
                    },
                    {
                        "title": "Contact Forms",
                        "icon": "contact_mail",
                        "link": lambda request: "/admin/app/contactformsubmission/",
                    },
                ],
            },
            {
                "title": "Product Management",
                "separator": True,
                "items": [
                    {
                        "title": "Product Categories",
                        "icon": "category",
                        "link": lambda request: "/admin/app/productcategory/",
                    },
                    {
                        "title": "Products",
                        "icon": "inventory",
                        "link": lambda request: "/admin/app/product/",
                    },
                    {
                        "title": "Product Status",
                        "icon": "assignment_turned_in",
                        "link": lambda request: "/admin/app/productstatus/",
                    },
                    {
                        "title": "Price List",
                        "icon": "list_alt",
                        "link": lambda request: "/admin/app/pricelist/",
                    },
                ],
            },
            {
                "title": "Content Management",
                "separator": True,
                "items": [
                    {
                        "title": "Blog Posts",
                        "icon": "article",
                        "link": lambda request: "/admin/app/blogpost/",
                    },
                    {
                        "title": "Blog Categories",
                        "icon": "bookmark",
                        "link": lambda request: "/admin/app/blogcategory/",
                    },
                    {
                        "title": "SEO Pages",
                        "icon": "description",
                        "link": lambda request: "/admin/app/pageseo/",
                    },
                ],
            },
            {
                "title": "User Management",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": lambda request: "/admin/auth/user/",
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": lambda request: "/admin/auth/group/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "app.product",
                "app.productcategory", 
                "app.productstatus",
                "app.pricelist",
            ],
            "items": [
                {
                    "title": "Product Categories",
                    "link": lambda request: "/admin/app/productcategory/",
                },
                {
                    "title": "Products", 
                    "link": lambda request: "/admin/app/product/",
                },
                {
                    "title": "Product Status",
                    "link": lambda request: "/admin/app/productstatus/",
                },
                {
                    "title": "Price Lists",
                    "link": lambda request: "/admin/app/pricelist/",
                },
            ],
        },
        {
            "models": [
                "app.blogpost",
                "app.blogcategory",
                "app.pageseo",
            ],
            "items": [
                {
                    "title": "Blog Posts",
                    "link": lambda request: "/admin/app/blogpost/",
                },
                {
                    "title": "Blog Categories",
                    "link": lambda request: "/admin/app/blogcategory/",
                },
                {
                    "title": "SEO Pages",
                    "link": lambda request: "/admin/app/pageseo/",
                },
            ],
        },
        {
            "models": [
                "app.enquiry",
                "app.contactformsubmission",
            ],
            "items": [
                {
                    "title": "Enquiries",
                    "link": lambda request: "/admin/app/enquiry/",
                },
                {
                    "title": "Contact Forms",
                    "link": lambda request: "/admin/app/contactformsubmission/",
                },
            ],
        },
    ],
}

def environment_callback(request):
    """Callback to show environment in admin header"""
    # if not DEBUG:
    #     return ["Production", "success"]
    return ["Production", "success"]  # [label, color]

